package com.hx.codec.constants;

/**
 * DataType
 *
 * @author Jerry.X.He
 * @version 1.0
 * @date 2021/9/23 17:11
 */
public enum DataType {

    // ------------------------------------------ basic types ------------------------------------------

    BYTE,
    UNSIGNED_BYTE,
    WORD,
    UNSIGNED_WORD,
    DWORD,
    QWORD,

    // ------------------------------------------ array types ------------------------------------------

    BYTE_ARRAY,
    UNSIGNED_BYTE_ARRAY,
    WORD_ARRAY,
    UNSIGNED_WORD_ARRAY,
    DWORD_ARRAY,
    QWORD_ARRAY,
    GENERIC_BEAN_ARRAY,

    BYTE_ARRAY_WITH_LEN,
    UNSIGNED_BYTE_ARRAY_WITH_LEN,
    WORD_ARRAY_WITH_LEN,
    UNSIGNED_WORD_ARRAY_WITH_LEN,
    DWORD_ARRAY_WITH_LEN,
    QWORD_ARRAY_WITH_LEN,
    GENERIC_BEAN_ARRAY_WITH_LEN,

    BYTE_ARRAY_WITH_ELE_LEN,
    UNSIGNED_BYTE_ARRAY_WITH_ELE_LEN,
    WORD_ARRAY_WITH_ELE_LEN,
    UNSIGNED_WORD_ARRAY_WITH_ELE_LEN,
    DWORD_ARRAY_WITH_ELE_LEN,
    QWORD_ARRAY_WITH_ELE_LEN,
    GENERIC_BEAN_ARRAY_WITH_ELE_LEN,

    BYTE_ARRAY_WITH_EXACTLY_LEN,
    UNSIGNED_BYTE_ARRAY_WITH_EXACTLY_LEN,
    WORD_ARRAY_WITH_EXACTLY_LEN,
    UNSIGNED_WORD_ARRAY_WITH_EXACTLY_LEN,
    DWORD_ARRAY_WITH_EXACTLY_LEN,
    QWORD_ARRAY_WITH_EXACTLY_LEN,
    GENERIC_BEAN_ARRAY_WITH_EXACTLY_LEN,

    // ------------------------------------------ collection types ------------------------------------------

    BYTE_COLLECTION,
    UNSIGNED_BYTE_COLLECTION,
    WORD_COLLECTION,
    UNSIGNED_WORD_COLLECTION,
    DWORD_COLLECTION,
    QWORD_COLLECTION,
    GENERIC_BEAN_COLLECTION,
    SCHEMA_REGISTRY_BASED_COLLECTION,

    BYTE_COLLECTION_WITH_LEN,
    UNSIGNED_BYTE_COLLECTION_WITH_LEN,
    WORD_COLLECTION_WITH_LEN,
    UNSIGNED_WORD_COLLECTION_WITH_LEN,
    DWORD_COLLECTION_WITH_LEN,
    QWORD_COLLECTION_WITH_LEN,
    GENERIC_BEAN_COLLECTION_WITH_LEN,
    SCHEMA_REGISTRY_BASED_COLLECTION_WITH_LEN,

    BYTE_COLLECTION_WITH_ELE_LEN,
    UNSIGNED_BYTE_COLLECTION_WITH_ELE_LEN,
    WORD_COLLECTION_WITH_ELE_LEN,
    UNSIGNED_WORD_COLLECTION_WITH_ELE_LEN,
    DWORD_COLLECTION_WITH_ELE_LEN,
    QWORD_COLLECTION_WITH_ELE_LEN,
    GENERIC_BEAN_COLLECTION_WITH_ELE_LEN,

    BYTE_COLLECTION_WITH_EXACTLY_LEN,
    UNSIGNED_BYTE_COLLECTION_WITH_EXACTLY_LEN,
    WORD_COLLECTION_WITH_EXACTLY_LEN,
    UNSIGNED_WORD_COLLECTION_WITH_EXACTLY_LEN,
    DWORD_COLLECTION_WITH_EXACTLY_LEN,
    QWORD_COLLECTION_WITH_EXACTLY_LEN,
    GENERIC_BEAN_COLLECTION_WITH_EXACTLY_LEN,
    SCHEMA_REGISTRY_BASED_COLLECTION_WITH_EXACTLY_LEN,

    // ------------------------------------------ string types ------------------------------------------

    BCD_8421_STRING_WITH_LEN,
    BCD_8421_STRING_WITH_FIXED_LEN,
    BCD_8421_STRING_WITH_EXACTLY_LEN,
    BCD_8421_BIG_DECIMAL_WITH_ONE_BYTE_LEN,
    CHARSET_ENCODING_STRING,
    CHARSET_ENCODING_WITH_LEN_STRING,
    CHARSET_ENCODING_WITH_FIXED_LEN_STRING,

    // ------------------------------------------ entity types ------------------------------------------

    GENERIC_BEAN,

    // ------------------------------------------ map types ------------------------------------------

    GENERIC_MAP,
    GENERIC_MAP_WITH_LEN,
    GENERIC_MAP_WITH_EXACTLY_LEN,
    SCHEMA_REGISTRY_BASED_MAP,
    SCHEMA_REGISTRY_BASED_MAP_WITH_LEN,
    SCHEMA_REGISTRY_BASED_MAP_WITH_EXACTLY_LEN,

    // ------------------------------------------ other types ------------------------------------------

    PADDING_BYTE,
    PADDING_BYTES,

}
